marks/urls.py
from django.conf.urls import url

from .import views

app_name = 'marks'

urlpatterns = [
    url(r'^home', views.home, name="home"),
    url(r'^teacher_login', views.teacher_login, name="teacher_login"),
    url(r'^upload', views.upload, name="upload"),
    url(r'^edit_marks', views.edit_marks, name="edit_marks"),
    url(r'^submit_marks', views.submit_marks, name="submit_marks"),
    url(r'^view_marks', views.view_marks, name="view_marks"),
    url(r'^logout', views.logout, name="logout")
]

marksapp_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^marks/', include('marks.urls'))
]

marks/models.py
from django.db import models

class Subject(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Batch(models.Model):
    SEMESTER_CHOICES = [(i, i) for i in range(1, 9)]
    STREAM_CHOICES = (
        ("cse", "Computer Science"),
        ("ece", "Electronics and Communication"),
        ("mae", "Mechanical and Automation"),
        ("it", "Information Technology"),
        ("eee", "Electrical and Electronics")
    )
    name = models.CharField(max_length=5)
    subjects = models.ManyToManyField(Subject)
    semester = models.IntegerField(choices=SEMESTER_CHOICES)
    stream = models.CharField(max_length=3, choices=STREAM_CHOICES)

    def __str__(self):
        return self.name


class Student(models.Model):
    batch = models.ForeignKey(Batch)
    # subjects = models.ManyToManyField(Subject)
    name = models.CharField(max_length=250)
    roll_no = models.CharField(max_length=15, primary_key=True)
    phone = models.CharField(max_length=12)

    def __str__(self):
        return self.name
    

class Teacher(models.Model):
    name = models.CharField(max_length=250)
    phone = models.CharField(max_length=12)
    email = models.EmailField(max_length=250)
    password = models.CharField(max_length=16)

    def __str__(self):
        return self.name

class BatchSubject(models.Model):
    teacher = models.ForeignKey(Teacher)
    subject = models.ForeignKey(Subject)
    batch = models.ForeignKey(Batch)

    def __str__(self):
        return self.teacher.name


class Marks(models.Model):
    student = models.ForeignKey(Student)
    subject = models.ForeignKey(Subject)
    first_sessional = models.FloatField(null=True)
    second_sessional = models.FloatField(null=True)
    internal_assessment = models.IntegerField(null=True)
    total_internal_marks = models.IntegerField(null=True)


class Coordinator(models.Model):
    teacher = models.ForeignKey(Teacher)
    batch = models.ForeignKey(Batch)

    def __str__(self):
        return self.batch.name

marks/forms.py
from django import forms
from django.forms import formset_factory

from .models import Teacher, Marks

class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = ['email', 'password']
        widgets = {
            'email': forms.TextInput(attrs={
                        'class': 'mdl-textfield__input',
                        'type': 'email',
                        'id': 'user'
                }),
            'password': forms.PasswordInput(attrs={
                        'class': 'mdl-textfield__input',
                        'type': 'password',
                        'id': 'password'
                })
        }

class UploadFileForm(forms.Form):
    file = forms.FileField()

class MarksForm(forms.ModelForm):
    class Meta:
        model = Marks
        fields = ['student', 'first_sessional', 'second_sessional', 'internal_assessment']

MarksFormSet = formset_factory(MarksForm)

marks/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from .models import Batch, Subject, Student, Teacher, Marks, BatchSubject, Coordinator
from .forms import TeacherForm, MarksFormSet, UploadFileForm
import django_excel as excel
import pyexcel.ext.xlsx
import openpyxl
import math

def home(request):
    return render(request, "marks/home.html")

def teacher_login(request):
    form = TeacherForm
    context = {
        'form': form
    }
    if request.POST:
        email= request.POST['email']
        if Teacher.objects.filter(email=email).exists():
            teacher = Teacher.objects.get(email=email)
            if teacher.password == request.POST['password']:
                is_coordinator = False
                coordinator_batch = None
                request.session['teacher_id'] = teacher.id
                batch_subject = BatchSubject.objects.filter(teacher=teacher)
                if Coordinator.objects.filter(teacher=teacher).exists():
                    is_coordinator = True
                    coordinator = Coordinator.objects.get(teacher=teacher)
                    coordinator_batch = coordinator.batch
                context = {
                    "teacher": teacher,
                    'batch_subject': batch_subject,
                    "is_coordinator": is_coordinator,
                    "coordinator_batch": coordinator_batch,
                }
                return render(request, "marks/dashboard.html", context)
            else:
                return redirect(reverse('marks:teacher_login')) 
        else: 
            return redirect(reverse('marks:teacher_login'))
    elif request.session.get('teacher_id'):
        teacher_id = request.session['teacher_id']
        teacher = Teacher.objects.get(pk=teacher_id)
        is_coordinator = False
        coordinator_batch = None
        batch_subject = BatchSubject.objects.filter(teacher=teacher)
        if Coordinator.objects.filter(teacher=teacher).exists():
            is_coordinator = True
            coordinator = Coordinator.objects.get(teacher=teacher)
            coordinator_batch = coordinator.batch
        context = {
            "teacher": teacher,
            'batch_subject': batch_subject,
            "is_coordinator": is_coordinator,
            "coordinator_batch": coordinator_batch,
        }
        return render(request, "marks/dashboard.html", context)
    else: 
        return render(request, "marks/teacher_login.html", context)

def upload(request):
    if request.method == "POST":
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            filehandle = request.FILES['file']
            return excel.make_response(filehandle.get_sheet(), "csv", file_name="download")
    else:
        form = UploadFileForm()
    context = {
        "form": form,
    }
    return render(request, "marks/upload_form.html", context)

def edit_marks(request):
    batch_subject_id = request.POST['batch_subject_id']
    exam_type = request.POST['exam_type']
    batch_subject = BatchSubject.objects.get(pk=batch_subject_id)
    batch = batch_subject.batch
    subject = batch_subject.subject
    student_list = Student.objects.filter(batch=batch)
    student_marks_list = []
    for student in student_list:
        student_details = {}
        Marks.objects.get_or_create(subject=subject, student=student)
        marks = Marks.objects.get(subject=subject, student=student)
        student_details['marks'] = marks
        student_details['student'] = Student.objects.get(pk=student.roll_no)
        student_marks_list.append(student_details)
    context = {
        "student_list": student_list,
        "batch_subject_id": batch_subject_id,
        "exam_type": exam_type,
        "student_marks_list": student_marks_list,
    }
    return render(request, "marks/edit_marks.html", context)

def submit_marks(request):
    print(request.POST)
    dict_post_data = request.POST
    exam_type = dict_post_data['exam_type']
    print(exam_type)
    batch_subject_id = dict_post_data['batch_subject_id']
    batch_subject = BatchSubject.objects.get(pk=batch_subject_id)
    batch = batch_subject.batch
    subject = batch_subject.subject
    student_list = Student.objects.filter(batch=batch)
    for student in student_list:
        if student.roll_no in dict_post_data:
            marks = dict_post_data[student.roll_no]
            Marks.objects.get(subject=subject, student=student)
            marks_field = Marks.objects.get(subject=subject, student=student)
            if exam_type == 'first_sessional' and marks != '':
                marks_field.first_sessional = float(marks)
            elif exam_type == 'second_sessional' and marks != '':
                marks_field.second_sessional = float(marks)
            elif exam_type == "internal_assessment" and marks != '':
                marks_field.internal_assessment = int(marks)
            if marks_field.first_sessional is not None and marks_field.second_sessional is not None \
            and marks_field.internal_assessment is not None:
                first = marks_field.first_sessional
                second = marks_field.second_sessional
                internal = marks_field.internal_assessment
                total = math.ceil(first / 3) + math.ceil(second / 3) + internal
                marks_field.total_internal_marks = total
            marks_field.save() 
    return redirect(reverse('marks:teacher_login'))

def view_marks(request):
    exam_type = request.POST['exam_type']
    batch_name = request.POST['batch']
    batch = Batch.objects.get(name=batch_name)
    subjects = batch.subjects.all()
    marks_list = []
    subject_teachers = ['', '']
    headers = ['Roll No', 'Name']
    for subject in subjects: 
        headers.append(subject.name)
        sub_teacher = BatchSubject.objects.get(batch=batch, subject=subject).teacher.name
        subject_teachers.append(sub_teacher)
    print(headers)
    marks_list.append(headers)
    marks_list.append(subject_teachers)
    student_list = Student.objects.filter(batch=batch)
    for student in student_list:
        print(student)
        marks_student = []
        marks_student.append(student.roll_no)
        marks_student.append(student.name)
        for subject in subjects:
            print(subject)
            marks = Marks.objects.get(student=student, subject=subject)
            if exam_type == 'first_sessional':
                print(marks.first_sessional)
                marks_student.append(marks.first_sessional)
            elif exam_type == 'second_sessional':
                print(marks.second_sessional)
                marks_student.append(marks.second_sessional)
            if exam_type == 'total_internal_marks':
                print(marks.total_internal_marks)
                marks_student.append(marks.total_internal_marks)
        marks_list.append(marks_student)
    print(marks_list)
    wb = openpyxl.Workbook()
    sheet = wb.get_sheet_by_name('Sheet')
    i = 1
    for line in marks_list:
        sheet.append(line)
    # for marks in marks_list:
    #     print(marks)
    #     j = 1
    #     for item in marks:
    #         sheet.cell(row=i, column=j, value=item)
    #         j += 1
    #     i += 1
    response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetm.sheet')
    response['Content-Disposition'] = 'attachment; filename=mydata.xlsx'
    wb.save(response)
    return response

def logout(request):
    try:
        del request.session['teacher_id']
        return redirect(reverse("marks:teacher_login"))
    except KeyError:
        pass
    return redirect(reverse("marks:teacher_login"))

marks/templates/marks/dashboard.html
{% extends 'base.html' %}

{% block header %}
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header mdl-layout--fixed-tabs">
    <header class="mdl-layout__header">
        <div class="mdl-layout-icon"></div>
        <div class="mdl-layout__header-row">
          <span class="mdl-layout__title">MarksApp</span>
          <div class="mdl-layout-spacer"></div>
          <nav class="mdl-navigation mdl-layout--large-screen-only">
            <a class="mdl-navigation__link" href="{% url 'marks:home' %}">Home</a>
            <a class="mdl-navigation__link" href="#">About</a>
            <a class="mdl-navigation__link" href="{% url 'marks:logout' %}">Logout</a>
          </nav>
        </div>
        <div class="mdl-layout__tab-bar mdl-js-ripple-effect">
          <a href="#teacher-tab" class="mdl-layout__tab is-active">Teacher</a>
          {% if is_coordinator %}
          <a href="#coordinator-tab" class="mdl-layout__tab">Coordinator</a>
          {% endif %}
        </div>
    </header>
    <div class="mdl-layout__drawer mdl-layout--small-screen-only">
    <span class="mdl-layout__title">Marksapp</span>
    <nav class="mdl-navigation">
      <a class="mdl-navigation__link" href="{% url 'marks:home' %}">Home</a>
      <a class="mdl-navigation__link" href="#">About</a>
      <a class="mdl-navigation__link" href="{% url 'marks:logout' %}">Logout</a>
    </nav>
    </div>
{% endblock %}

{% block page-content %}

<section class="mdl-layout__tab-panel is-active" id="teacher-tab">
  <div class="mdl-grid">
    <div class="page-content mdl-cell mdl-cell--4-col mdl-cell--4-col-phone centered">
    <h5>Hi, {{ teacher.name }}</h5>
      <form action="{% url 'marks:edit_marks' %}" method="POST">{% csrf_token %}
          <div class="mdl-selectfield mdl-js-selectfield">
            <select id="batch-subject-id" name="batch_subject_id" class="browser-default subject-select">
                <option value="" disabled selected>Select your batch and subject</option>
                {% for bs in batch_subject %} 
                <option value="{{ bs.id }}" type="text">{{ bs.batch }} -- {{ bs.subject }}</option>
                {% endfor %}
            </select>
            <label class="mdl-selectfield__label" for="batch-subject-id">Select Subject</label>
          </div>
    
        <div class="mdl-selectfield mdl-js-selectfield">
            <select name="exam_type" class="browser-default exam-select">
                <option value="" disabled selected>Select exam</option>
                <option value="first_sessional">First Sessional</option>
                <option value="second_sessional">Second Sessional</option>
                <option value="internal_assessment">Internal Assessment</option>
            </select>
            <label class="mdl-selectfield__label" for="exam_type">Select Exam</label>
        </div>
          <button type="submit" class="mdl-button mdl-js-button mdl-button--raised">Next</button>
      </form>
    </div>
  </div>
</section>

{% if is_coordinator %}
<section class="mdl-layout__tab-panel" id="coordinator-tab">
  <div class="mdl-grid">
    <div class="page-content mdl-cell mdl-cell--4-col mdl-cell--4-col-phone centered">
    <h5>Batch: {{ coordinator_batch }}</h5>
    <form action="{% url 'marks:view_marks' %}" method="POST">{% csrf_token %}
      <div class="mdl-selectfield mdl-js-selectfield">
        <label class="subject-label" for="subject">Select Exam</label>
        <select name="exam_type" class="browser-default exam-select">
            <option value="" disabled selected>Choose exam</option>
            <option value="first_sessional">First Sessional</option>
            <option value="second_sessional">Second Sessional</option>
            <option value="total_internal_marks">Total Internal Marks</option>
        </select>
      </div>
      <input type="hidden" name="batch" value="{{ coordinator_batch }}">
        <br>
        <button type="submit" class="mdl-button mdl-js-button mdl-button--raised">Next</button>
    </form>
    </div>
  </div>
</section>
{% endif %}
   
{% endblock %}

marks/templates/marks/edit_marks.html
{% extends 'base.html' %}

{% block header %}
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header mdl-layout--fixed-tabs">
    <header class="mdl-layout__header">
        <div class="mdl-layout-icon"></div>
        <div class="mdl-layout__header-row">
          <span class="mdl-layout__title">MarksApp</span>
          <div class="mdl-layout-spacer"></div>
          <nav class="mdl-navigation mdl-layout--large-screen-only">
            <a class="mdl-navigation__link" href="{% url 'marks:home' %}">Home</a>
            <a class="mdl-navigation__link" href="#">About</a>
            <a class="mdl-navigation__link" href="{% url 'marks:logout' %}">Logout</a>
          </nav>
        </div>
    </header>
    <div class="mdl-layout__drawer mdl-layout--small-screen-only">
    <span class="mdl-layout__title">Marksapp</span>
    <nav class="mdl-navigation">
      <a class="mdl-navigation__link" href="{% url 'marks:home' %}">Home</a>
      <a class="mdl-navigation__link" href="#">About</a>
      <a class="mdl-navigation__link" href="{% url 'marks:logout' %}">Logout</a>
    </nav>
    </div>
{% endblock %}

{% block page-content %}

<div class="mdl-grid">
    <div class="mdl-cell-12-col centered">
        <form action="submit_marks" method="POST">{% csrf_token %}
            <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
            <tr>
                <th class="mdl-data-table__cell--non-numeric">Roll No</th>
                <th class="mdl-data-table__cell--non-numeric">Name</th>
                {% if exam_type == 'first_sessional' %}
                <th class="mdl-data-table__cell--non-numeric">First Sessional</th>
                {% elif exam_type == 'second_sessional' %}
                <th class="mdl-data-table__cell--non-numeric">Second Sessional</th>
                {% elif exam_type == 'internal_assessment' %}
                <th class="mdl-data-table__cell--non-numeric">Internal Assessment</th>
                {% endif %}
            </tr>
            <input type="hidden" name="batch_subject_id" value="{{ batch_subject_id }}">
            <input type="hidden" name="exam_type" value="{{ exam_type }}">
            {% for student_marks in student_marks_list %}
            <tr>
                <td class="mdl-data-table__cell--non-numeric"><span>{{ student_marks.student.roll_no }}</span></td>
                <td class="mdl-data-table__cell--non-numeric"><span>{{ student_marks.student.name }}</span></td>
                <td class="mdl-data-table__cell--non-numeric">
                    <div class="mdl-textfield mdl-js-textfield marks-field">
                        {% if exam_type == 'first_sessional' %}
                        <input class="mdl-textfield__input" type="text" name="{{ student_marks.student.roll_no }}" value="{{ student_marks.marks.first_sessional|default_if_none:"" }}">
                        {% elif exam_type == 'second_sessional' %}
                        <input class="mdl-textfield__input" type="text" name="{{ student_marks.student.roll_no }}" value="{{ student_marks.marks.second_sessional|default_if_none:"" }}">
                        {% elif exam_type == 'internal_assessment' %}
                        <input class="mdl-textfield__input" type="text" name="{{ student_marks.student.roll_no }}" value="{{ student_marks.marks.internal_assessment|default_if_none:"" }}">
                        {% endif %}
                    </div>
                </td>
                <!-- <td class="mdl-data-table__cell--non-numeric">
                    <div class="mdl-textfield mdl-js-textfield marks-field">
                        <input class="mdl-textfield__input" type="text" name="{{ student_marks.roll_no }}_ss" value="{{ student_marks.marks.second_sessional|default_if_none:"" }}">
                    </div>
                </td>
                <td class="mdl-data-table__cell--non-numeric">
                    <div class="mdl-textfield mdl-js-textfield marks-field">
                        <input class="mdl-textfield__input" type="text"  name="{{ student_marks.roll_no }}_ia" value="{{ student_marks.marks.internal_assessment|default_if_none:"" }}">
                    </div>
                </td> -->
            </tr>
            {% endfor %}
            </table>
            <br>
            <button class="mdl-button mdl-js-button mdl-button--raised submit-marks">Submit</button>
        </form>
    </div>
</div>

{% endblock %}

marks/templates/marks/header.html
{% block header %}
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
    <header class="mdl-layout__header">
        <div class="mdl-layout-icon"></div>
        <div class="mdl-layout__header-row">
            <span class="mdl-layout__title">MarksApp</span>
            <div class="mdl-layout-spacer"></div>
            <nav class="mdl-navigation mdl-layout--large-screen-only">
                <a class="mdl-navigation__link" href="{% url 'marks:home' %}">Home</a>
                <a class="mdl-navigation__link" href="#">About</a>
            </nav>
        </div>
    </header>
    <div class="mdl-layout__drawer mdl-layout--small-screen-only">
        <span class="mdl-layout__title">Marksapp</span>
        <nav class="mdl-navigation">
          <a class="mdl-navigation__link" href="{% url 'marks:home' %}">Home</a>
          <a class="mdl-navigation__link" href="#">About</a>
        </nav>
    </div>

{% endblock %}

marks/templates/marks/home.html
{% extends 'base.html' %}

{% block header %}
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header mdl-layout--fixed-tabs">
    <header class="mdl-layout__header">
        <div class="mdl-layout-icon"></div>
        <div class="mdl-layout__header-row">
          <span class="mdl-layout__title">MarksApp</span>
          <div class="mdl-layout-spacer"></div>
          <nav class="mdl-navigation mdl-layout--large-screen-only">
            <a class="mdl-navigation__link" href="{% url 'marks:home' %}">Home</a>
            <a class="mdl-navigation__link" href="#">About</a>
          </nav>
        </div>
    </header>
    <div class="mdl-layout__drawer mdl-layout--small-screen-only">
    <span class="mdl-layout__title">Marksapp</span>
    <nav class="mdl-navigation">
      <a class="mdl-navigation__link" href="{% url 'marks:home' %}">Home</a>
      <a class="mdl-navigation__link" href="#">About</a>
    </nav>
    </div>
{% endblock %}

{% block page-content %}

<div class="mdl-grid card-grid">
  <!-- <div class="mdl-cell mdl-cell--4-col mdl-cell--4-col-phone mdl-cell--4-col-tablet area-item centered mdl-card mdl-shadow--2dp">
    <div class="mdl-card__title mdl-card--expand">
      <!--<h2 class="mdl-card__title-text"></h2>-->
      <!-- <i class="material-icons card-icon">school</i>
    </div>
    <div class="mdl-card__supporting-text">
      Students can view marks by entering their Enrolment No.
    </div>
    <div class="mdl-card__actions mdl-card--border">
      <a class="mdl-button mdl-button--accent mdl-js-button mdl-js-ripple-effect" href="student_area.php">
        Student Area
      </a>
    </div>          
  </div> -->
  <div class="mdl-cell mdl-cell--4-col mdl-cell--4-col-phone mdl-cell--4-col-tablet area-item centered mdl-card mdl-shadow--2dp">
    <div class="mdl-card__title mdl-card--expand">
      <i class="material-icons card-icon">assignment_ind</i>
    </div>
    <div class="mdl-card__supporting-text">
      Teachers can Login and enter student records and also enter or update their marks.
    </div>
    <div class="mdl-card__actions mdl-card--border">
      <a class="mdl-button mdl-button--accent mdl-js-button mdl-js-ripple-effect" href="{% url 'marks:teacher_login' %}">
        Teacher Area
      </a>
    </div>         
  </div>
  <div class="mdl-cell mdl-cell--4-col mdl-cell--4-col-phone mdl-cell--4-col-tablet area-item centered mdl-card mdl-shadow--2dp">
    <div class="mdl-card__title mdl-card--expand">
      <i class="material-icons card-icon">people</i>
    </div>
    <div class="mdl-card__supporting-text">
      The H.O.D can view marks of all the students in various subjects.
    </div>
    <div class="mdl-card__actions mdl-card--border">
      <a class="mdl-button mdl-button--accent mdl-js-button mdl-js-ripple-effect" href="{% url 'admin:index' %}">
        H.O.D Area
      </a>
    </div>
  </div>
</div>

{% endblock %}

marks/templates/marks/teacher_login.html
{% extends 'base.html' %}

{% block header %}
  {% include 'marks/header.html' %}
{% endblock %}

{% block page-content %}

    <section>
      <!-- <div class="page-content mdl-cell mdl-cell--8-col mdl-cell--12-col-phone centered"> -->
        <div class="mdl-grid">
          <div class="mdl-cell mdl-cell--4-col mdl-card mdl-shadow--2dp wrapper login-form centered">
            <div class="mdl-card__title text-center">
              <h2 class="mdl-card__title-text">Login</h2>
            </div>
            <form action="" method="POST">{% csrf_token %}
              <div class="mdl-card__supporting-text">
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                  {{ form.email }}
                  <label class="mdl-textfield__label" for="user">Email</label>
                </div>
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                  {{ form.password }}
                  <label class="mdl-textfield__label" for="password">Password</label>
                </div>
              </div>
              <div class="mdl-card__actions mdl-card--border text-center">
                <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--raised mdl-button--accent" name="submit" type="submit">
                  Login
                </button>
                <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
                  Signup
                </a>
              </div>
            </form>
          </div>
        </div>
      <!-- </div> -->
    </section>
   
{% endblock %}

marks/templates/marks/upload_form.html
{% extends 'base.html' %}

{% block header %}
  {% include 'marks/header.html' %}
{% endblock %}

{% block page-content %}

<section>
    <div class="mdl-grid">
        <div class="page-content mdl-cell mdl-cell--4-col mdl-cell--4-col-phone centered">
            {% if form.errors %}
                <p style="color: red;">
                    Please correct the error{{ form.errors|pluralize }} below.
                </p>
            {% endif %}

            <form action="{% url 'marks:import_sheet' %}" enctype="multipart/form-data"  method="post">{% csrf_token %}
                <table>
                    {{ form.as_table }}
                </table>
                <input type="submit" value="Submit">
            </form>
        </div>
    </div>
</section>

{% endblock %}

marks/templates/marks/view_marks.html
{% extends 'base.html' %}

{% block header %}
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header mdl-layout--fixed-tabs">
    <header class="mdl-layout__header">
        <div class="mdl-layout-icon"></div>
        <div class="mdl-layout__header-row">
          <span class="mdl-layout__title">MarksApp</span>
          <div class="mdl-layout-spacer"></div>
          <nav class="mdl-navigation mdl-layout--large-screen-only">
            <a class="mdl-navigation__link" href="{% url 'marks:home' %}">Home</a>
            <a class="mdl-navigation__link" href="#">About</a>
            <a class="mdl-navigation__link" href="{% url 'marks:logout' %}">Logout</a>
          </nav>
        </div>
    </header>
    <div class="mdl-layout__drawer mdl-layout--small-screen-only">
    <span class="mdl-layout__title">Marksapp</span>
    <nav class="mdl-navigation">
      <a class="mdl-navigation__link" href="{% url 'marks:home' %}">Home</a>
      <a class="mdl-navigation__link" href="#">About</a>
      <a class="mdl-navigation__link" href="{% url 'marks:logout' %}">Logout</a>
    </nav>
    </div>
{% endblock %}

{% block page-content %}

{% endblock %}